
spring:
  application:
    name: load-service

server:
  port: 9200

logging:
  level:
    ROOT: DEBUG

  # -- Configure for Ribbon:
#
#ping-server:
#  ribbon:
#    eureka:
#      enabled: false # Disable Default Ping
#    listOfServers: localhost:8001,localhost:8002,localhost:8003
#    ServerListRefreshInterval: 15000

  # -- Configure Discovery Client (Eureka Client).
  # Configure this application to known "Service Registration".

eureka:
  instance:
    appname: load-service  # ==> This is an instance of XYZ-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
